<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

// Thumbnails and lightbox images are pre-generated by scripts/optimize-photos.js
// (runs automatically before dev/build) so the browser never fetches the
// multi-MB originals in src/photos/planespotting/.
const thumbModules = import.meta.glob('../photos/planespotting/_generated/thumbs/*.webp', { eager: true, import: 'default' })
const fullModules = import.meta.glob('../photos/planespotting/_generated/full/*.webp', { eager: true, import: 'default' })

const DATE_NAME_PATTERN = /^(\d{4})-(\d{2})-(\d{2})_(\d{2})-(\d{2})-(\d{2})(?:-\d+)?$/
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

function baseName(path) {
  return path.replace(/^.*\//, '').replace(/\.[^.]+$/, '')
}

function toCaption(name) {
  const m = name.match(DATE_NAME_PATTERN)
  if (!m) return name.replace(/[-_]+/g, ' ')
  const [, year, month, day, hour, min, sec] = m
  return `Shot on ${year} ${MONTHS[Number(month) - 1]} ${Number(day)} ${hour}:${min}:${sec}`
}

function keyByBase(modules) {
  const map = {}
  for (const [path, mod] of Object.entries(modules)) map[baseName(path)] = mod
  return map
}

const thumbs = keyByBase(thumbModules)
const fulls = keyByBase(fullModules)

const photos = Object.keys(thumbs)
  .map(name => ({
    thumbSrc: thumbs[name],
    fullSrc: fulls[name] ?? thumbs[name],
    sortKey: name,
    caption: toCaption(name),
  }))
  .sort((a, b) => a.sortKey.localeCompare(b.sortKey))

const activeIndex = ref(null)

function open(i) {
  activeIndex.value = i
}

function close() {
  activeIndex.value = null
}

function next() {
  activeIndex.value = (activeIndex.value + 1) % photos.length
}

function prev() {
  activeIndex.value = (activeIndex.value - 1 + photos.length) % photos.length
}

function onKeydown(e) {
  if (activeIndex.value === null) return
  if (e.key === 'Escape') close()
  if (e.key === 'ArrowRight') next()
  if (e.key === 'ArrowLeft') prev()
}

onMounted(() => window.addEventListener('keydown', onKeydown))
onUnmounted(() => window.removeEventListener('keydown', onKeydown))
</script>

<template>
  <section class="pt-20 sm:pt-32 pb-20">
    <h2 class="text-s font-mono text-muted uppercase tracking-widest mb-10">Gallery</h2>

    <p class="text-sm text-muted leading-relaxed mb-10">
      A few shots from planespotting trips. Click a photo to view it larger.
    </p>

    <div v-if="photos.length" class="grid grid-cols-2 sm:grid-cols-3 gap-3">
      <button
        v-for="(photo, i) in photos"
        :key="photo.sortKey"
        class="group block aspect-square overflow-hidden rounded-lg border border-fg/8 hover:border-accent/20 transition-colors"
        @click="open(i)"
      >
        <img
          :src="photo.thumbSrc"
          :alt="photo.caption"
          loading="lazy"
          class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
        />
      </button>
    </div>

    <p v-else class="text-sm text-muted/50 italic">
      Photos coming soon.
    </p>

    <div
      v-if="activeIndex !== null"
      class="fixed inset-0 z-[100] bg-black/90 flex items-center justify-center p-4 sm:p-10"
      @click.self="close"
    >
      <button
        class="absolute top-4 right-4 text-white/70 hover:text-white transition-colors"
        aria-label="Close"
        @click="close"
      >
        <svg viewBox="0 0 24 24" class="w-7 h-7" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round">
          <path d="M18 6L6 18M6 6l12 12"/>
        </svg>
      </button>

      <button
        v-if="photos.length > 1"
        class="absolute left-2 sm:left-6 top-1/2 -translate-y-1/2 text-white/70 hover:text-white transition-colors"
        aria-label="Previous photo"
        @click.stop="prev"
      >
        <svg viewBox="0 0 24 24" class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
          <path d="M15 18l-6-6 6-6"/>
        </svg>
      </button>

      <figure class="max-w-full max-h-full flex flex-col items-center">
        <img :src="photos[activeIndex].fullSrc" :alt="photos[activeIndex].caption" class="max-w-full max-h-[80vh] rounded-lg object-contain" />
        <figcaption class="text-sm text-white/60 font-mono mt-3">{{ photos[activeIndex].caption }}</figcaption>
      </figure>

      <button
        v-if="photos.length > 1"
        class="absolute right-2 sm:right-6 top-1/2 -translate-y-1/2 text-white/70 hover:text-white transition-colors"
        aria-label="Next photo"
        @click.stop="next"
      >
        <svg viewBox="0 0 24 24" class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
          <path d="M9 18l6-6-6-6"/>
        </svg>
      </button>
    </div>
  </section>
</template>
