// Thumbnails and lightbox images are pre-generated by scripts/optimize-photos.js
// (runs automatically before dev/build) so the browser never fetches the
// multi-MB originals in src/photos/<collection>/. Every direct subfolder of
// src/photos is treated as its own collection.
const thumbModules = import.meta.glob('../photos/*/_generated/thumbs/*.webp', { eager: true, import: 'default' })
const fullModules = import.meta.glob('../photos/*/_generated/full/*.webp', { eager: true, import: 'default' })

const DATE_NAME_PATTERN = /^(\d{4})-(\d{2})-(\d{2})_(\d{2})-(\d{2})-(\d{2})(?:-\d+)?$/
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

// Hand-written copy for known collections; anything else falls back to a
// title-cased folder name and a generic photo-count description.
const COLLECTION_META = {
  planespotting: {
    title: 'Planespotting',
    description: 'Shots from planespotting trips.',
  },
}

function parseModulePath(path) {
  const m = path.match(/\/photos\/([^/]+)\/_generated\/(?:thumbs|full)\/([^/]+)\.webp$/)
  return m ? { collection: m[1], name: m[2] } : null
}

function toCaption(name) {
  const m = name.match(DATE_NAME_PATTERN)
  if (!m) return name.replace(/[-_]+/g, ' ')
  const [, year, month, day, hour, min, sec] = m
  return `Shot on ${year} ${MONTHS[Number(month) - 1]} ${Number(day)} ${hour}:${min}:${sec}`
}

function titleCase(slug) {
  return slug.replace(/[-_]+/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
}

function buildCollections() {
  const byCollection = {}

  for (const [modules, key] of [[thumbModules, 'thumbSrc'], [fullModules, 'fullSrc']]) {
    for (const [path, mod] of Object.entries(modules)) {
      const parsed = parseModulePath(path)
      if (!parsed) continue
      const photos = (byCollection[parsed.collection] ??= {})
      const photo = (photos[parsed.name] ??= {})
      photo[key] = mod
    }
  }

  return Object.entries(byCollection)
    .map(([slug, photosByName]) => {
      const photos = Object.entries(photosByName)
        .map(([name, srcs]) => ({
          sortKey: name,
          thumbSrc: srcs.thumbSrc,
          fullSrc: srcs.fullSrc ?? srcs.thumbSrc,
          caption: toCaption(name),
        }))
        .sort((a, b) => b.sortKey.localeCompare(a.sortKey)) // newest first

      const meta = COLLECTION_META[slug] ?? {}
      return {
        slug,
        title: meta.title ?? titleCase(slug),
        description: meta.description ?? `${photos.length} photo${photos.length === 1 ? '' : 's'}.`,
        photos,
        cover: photos[0]?.thumbSrc ?? null,
      }
    })
    .sort((a, b) => a.slug.localeCompare(b.slug))
}

export const collections = buildCollections()

export function getCollection(slug) {
  return collections.find(c => c.slug === slug) ?? null
}
