// Thumbnails and lightbox copies are generated by scripts/optimize-photos.js
// and live in R2, not in the repo — the browser never fetches the multi-MB
// originals, and neither does anyone cloning the project.
//
// This reads the manifest that script commits rather than globbing local
// files, so the build needs no photos on disk. Every key under `collections`
// is its own collection.
import manifest from '../generated/photos.json'

const DATE_NAME_PATTERN = /^(\d{4})-(\d{2})-(\d{2})_(\d{2})-(\d{2})-(\d{2})(?:-\d+)?$/
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

// Hand-written copy for known collections; anything else falls back to a
// title-cased folder name and a generic photo-count description.
const COLLECTION_META = {
  planespotting: {
    title: 'Planespotting',
    description: 'Shots from planespotting trips.',
  },
}

function urlFor(collection, variant, name) {
  const { base, prefix } = manifest
  return `${base}/${prefix}/${collection}/${variant}/${encodeURIComponent(name)}.webp`
}

function toCaption(name) {
  const m = name.match(DATE_NAME_PATTERN)
  if (!m) return name.replace(/[-_]+/g, ' ')
  const [, year, month, day, hour, min, sec] = m
  return `Shot on ${year} ${MONTHS[Number(month) - 1]} ${Number(day)} ${hour}:${min}:${sec}`
}

function titleCase(slug) {
  return slug.replace(/[-_]+/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
}

function buildCollections() {
  return Object.entries(manifest.collections ?? {})
    .map(([slug, entries]) => {
      const photos = (entries ?? [])
        .map(({ name }) => ({
          sortKey: name,
          thumbSrc: urlFor(slug, 'thumbs', name),
          fullSrc: urlFor(slug, 'full', name),
          caption: toCaption(name),
        }))
        .sort((a, b) => b.sortKey.localeCompare(a.sortKey)) // newest first

      const meta = COLLECTION_META[slug] ?? {}
      return {
        slug,
        title: meta.title ?? titleCase(slug),
        description: meta.description ?? `${photos.length} photo${photos.length === 1 ? '' : 's'}.`,
        photos,
        cover: photos[0]?.thumbSrc ?? null,
      }
    })
    .sort((a, b) => a.slug.localeCompare(b.slug))
}

export const collections = buildCollections()

export function getCollection(slug) {
  return collections.find(c => c.slug === slug) ?? null
}
